import { Geist, Geist_Mono, Assistant } from "next/font/google";
import "./globals.css";
import LoadingOverlay from "./components/LoadingOverlay";
import { CartProvider } from "@/context/CartContext"; // ✅ Import the CartProvider
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const assistant = Assistant({
  variable: "--font-assistant",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Parfumerie Ines",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${assistant.variable} antialiased`}
      >
        <CartProvider> {/* ✅ Wrap your entire app with CartProvider */}
          <Toaster position="top-center" />
          <LoadingOverlay />
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
