import { Geist, Geist_Mono, Assistant } from "next/font/google";
import "../globals.css";
import Leftsidebar from "../components/Leftsidebar";
import { Toaster } from "react-hot-toast";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const assistant = Assistant({
  variable: "--font-assistant",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Bey&Bey",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${assistant.variable} antialiased`}>
        <div className="flex flex-col lg:flex-row">
          <Leftsidebar />
          <Toaster position="top-center" reverseOrder={false} />
          {children}
        </div>
 
  
      </body>
    </html>
  );
}
